Admin settings
brenoalvs/monk pull request #10
Opened 2016-09-20 18:26 UTC by chandonn

Related to #1

2016-09-21 23:29 UTC, brenoalvs commented
@chandonn you'll must store the select template in `/admin/partials` folder.
Also needed some code standard fixes. Please check this.

2016-09-26 18:30 UTC, brenoalvs commented on admin/class-monk-admin.php
> +			3 );
Wrong close brackets.

2016-09-26 18:31 UTC, brenoalvs commented on admin/class-monk-admin.php
> +			'General options',
Section and Fields names needs localization using `__` function

2016-09-26 18:31 UTC, brenoalvs commented on admin/class-monk-admin.php
> +			'generalOptions',
Don't use camelCase in slugs

2016-09-26 18:32 UTC, brenoalvs commented on admin/class-monk-admin.php
> +		echo _e( 'Adjust the way you want', 'monk');
`_e` is a `echo` with internationalization, `echo` is not needed here.

2016-09-26 18:32 UTC, brenoalvs commented on admin/partials/admin-monk-options.php
> +			settings_fields( 'generalOptions' );
Same camelCase problem here.

2016-09-26 18:33 UTC, brenoalvs commented on admin/partials/admin-monk-select-render.php
> +	<select name='monk_language[language_select]'>
Don't use single quotes in HTML.
Localize with `_e` function the option tag label

2016-09-26 18:33 UTC, brenoalvs requested changes

2016-09-26 18:39 UTC, brenoalvs commented on admin/class-monk-admin.php
> +			wp_enqueue_style( $this->monk, plugin_dir_url( __FILE__ ) . 'css/monk-admin.css', array(), $this->version, 'all' );
Wrong indentation here.

2016-09-26 18:40 UTC, brenoalvs commented on admin/partials/admin-monk-select-render.php
> +		<option value="portuguese"<?php selected( $options['language_select'], "portuguese" ); ?>>Portuguese</option>
In PHP functions use single quotes.
Remember in HTML = double quotes, PHP = single quotes

2016-09-26 18:41 UTC, brenoalvs requested changes
@chandonn some changes are not finished yet and I added a new one.

2016-09-27 12:57 UTC, chandonn commented on admin/class-monk-admin.php
> +			wp_enqueue_style( $this->monk, plugin_dir_url( __FILE__ ) . 'css/monk-admin.css', array(), $this->version, 'all' );
Fixed

2016-09-27 12:58 UTC, chandonn commented on admin/partials/admin-monk-select-render.php
> +		<option value="portuguese"<?php selected( $options['language_select'], "portuguese" ); ?>>Portuguese</option>
Fixed

2016-09-27 13:03 UTC, chandonn commented on admin/class-monk-admin.php
> +		echo _e( 'Adjust the way you want', 'monk');
Fixed

2016-09-27 13:03 UTC, chandonn commented on admin/partials/admin-monk-options.php
> +			settings_fields( 'generalOptions' );
Fixed

2016-09-27 13:03 UTC, chandonn commented on admin/class-monk-admin.php
> +			'generalOptions',
Fixed

2016-09-27 13:16 UTC, chandonn commented on admin/class-monk-admin.php
> +			'General options',
Fixed

2016-09-27 13:17 UTC, chandonn commented on admin/class-monk-admin.php
> +			3 );
Fixed

2016-09-27 16:49 UTC, brenoalvs approved these changes

2016-09-27 16:49 UTC, merged