Rewrite api
brenoalvs/monk pull request #126
Opened 2017-01-27 11:58 UTC by chandonn

2017-02-02 21:10 UTC, raphaelkross commented on admin/class-monk-admin.php
> +				$query->set( 'mata_key', '_monk_post_language' );
meta_key instead mata_key ?

2017-02-02 21:13 UTC, raphaelkross commented on includes/class-monk-links.php
> +		if ( is_attachment() && isset( $_GET['attachment_id'] ) ) {
filter_input INPUT_GET could be used instead accessing the global directly?

2017-02-02 21:13 UTC, raphaelkross commented on includes/class-monk-links.php
> +		if ( isset( $_POST['wp_customize'], $_POST['customized'] ) ) {
filter_input INPUT_POST could be used instead accessing the global directly?

2017-02-03 16:12 UTC, brenoalvs commented on includes/class-monk-links.php
> +		$structure = get_option( 'permalink_structure', false );
You're using this in many methods.
Create a public property for this.

2017-02-03 16:48 UTC, chandonn commented on includes/class-monk-links.php
> +		$structure = get_option( 'permalink_structure', false );
Now the class has a method called 'monk_using_permalinks()'
Retrieves the structure or false, if the user is not using pretty permalinks
Have I found a good approach?

2017-02-07 03:32 UTC, brenoalvs requested changes

2017-02-07 03:32 UTC, brenoalvs commented on includes/class-monk-links.php
> +		$structure = get_option( 'permalink_structure', false );
What happens when `$structure` is `false`?
Why not use `monk_using_permalinks()` method here?

2017-02-07 03:32 UTC, brenoalvs commented on includes/class-monk-links.php
> +	public function monk_apply_slash() {
You're not using this method anywhere. Please remove it.

2017-02-07 03:32 UTC, brenoalvs commented on includes/class-monk-links.php
> +		if ( is_admin() || ! ( did_action( 'login_init' ) || did_action( 'template_redirect' ) ) ) {
Why we're checking by `template_redirect`?

2017-02-07 03:32 UTC, brenoalvs commented on includes/class-monk-links.php
> +				return trailingslashit( trailingslashit( $url ) . $language );
Do you REALLY need two `trailingslashit` functions?

2017-02-07 03:32 UTC, brenoalvs commented on includes/class-monk-links.php
> +	 * This function performs a redirect from the home url
Missing description about Search page.

2017-02-07 03:32 UTC, brenoalvs commented on includes/class-monk-links.php
> +		$site_language = get_option( 'monk_default_language', false );
Turn this variable into a class property. You may use it a lot.

2017-02-07 03:32 UTC, brenoalvs commented on includes/class-monk-links.php
> +		if ( empty( $language ) ) {
You need return a permalink always or you can broke the functionality.
You must encapsulate this change language process in another method, you're using it a lot in the methods below.

2017-02-07 03:32 UTC, brenoalvs commented on includes/class-monk-links.php
> +		$site_language = get_option( 'monk_default_language', false );
Use the new class property...

2017-02-07 03:32 UTC, brenoalvs commented on includes/class-monk-links.php
> +		if ( empty( $language ) ) {
... and the new encapsulated method.

2017-02-07 03:32 UTC, brenoalvs commented on includes/class-monk-links.php
> +			$language     = get_option( 'monk_default_language', false );
Why you need set `$language` here?

2017-02-07 03:32 UTC, brenoalvs commented on includes/class-monk.php
> +		$this->loader->add_action( 'template_redirect', $plugin_links, 'monk_redirect_search', 10 );
`monk_redirect_search` not exists.

2017-02-07 03:32 UTC, brenoalvs commented on includes/class-monk-links.php
> +	public function monk_need_canonical_redirect() {
Add more inline documentation in this method.
A lot of rules are applied here.

2017-02-07 03:32 UTC, brenoalvs commented on includes/class-monk.php
> +		$this->loader->add_action( 'template_redirect', $plugin_links, 'monk_redirect_home_url', 10, 2 );
You don't have any parameters in this action. Please, remove this.

2017-02-07 03:32 UTC, brenoalvs commented on includes/class-monk.php
> +		$this->loader->add_action( 'template_redirect', $plugin_links, 'monk_redirect_home_url', 10, 2 );
Why this cannot be made under `monk_need_canonical_redirect`?

2017-02-07 03:32 UTC, brenoalvs commented on widgets/class-monk-language-switcher.php
> +		$current_language     = get_query_var( 'lang' ) ? sanitize_text_field( wp_unslash( get_query_var( 'lang' ) ) ) : get_option( 'monk_default_language' );
I think you can remove `wp_unslash` from there.
We also need a default value like `get_option( 'monk_default_language', false );`

2017-02-07 03:32 UTC, brenoalvs commented on includes/class-monk-links.php
> +<?php
Review all code standards.
- Remove `@link` and `@author` tags, we can receive a lot of spam.
- Pay attention on white-spaces used in all methods.
- Keep consistent with other files.
- No blank lines before and after declaring a method.

2017-02-07 15:18 UTC, chandonn commented on includes/class-monk-links.php
> +			$language     = get_option( 'monk_default_language', false );
In the case we do not get any of the above listed content, the language is the site language, to avoid breaking the links with no redirection needed

2017-02-08 14:29 UTC, chandonn commented on includes/class-monk-links.php
> +<?php
Reviewed

2017-02-08 19:27 UTC, brenoalvs requested changes

2017-02-08 19:27 UTC, brenoalvs commented on includes/class-monk-links.php
> +		if ( empty( $lang ) ) {
Remove this verification

2017-02-08 19:27 UTC, brenoalvs commented on includes/class-monk-links.php
> +		if ( empty( $language ) ) {
You'll always have a site language.

2017-02-08 19:27 UTC, brenoalvs commented on includes/class-monk-links.php
> +		if ( is_home() && ( ! ( get_query_var( 'lang' ) || get_query_var( 's' ) ) || ! preg_match( $pattern, get_query_var( 'lang' ) ) ) ) {
Remove `preg_match`, use `in_array`.
Move this logic to canonical hook.

2017-02-08 19:27 UTC, brenoalvs commented on includes/class-monk-links.php
> +	public function monk_need_canonical_redirect() {
Change name to `monk_canonical_redirection`.

2017-02-14 01:40 UTC, closed without merging