Monk love
brenoalvs/monk pull request #146
Opened 2017-03-08 17:47 UTC by chandonn

New option in the Monk settings page

2017-03-11 02:42 UTC, brenoalvs requested changes

2017-03-11 02:42 UTC, brenoalvs commented on admin/partials/admin-monk-appreciation-render.php
> + * @since      0.1.0
Wrong `@since` tag this will be release at `0.3.0`.

2017-03-11 02:42 UTC, brenoalvs commented on admin/partials/admin-monk-appreciation-render.php
> +<label for="appreciate-monk">
Wrong indentation.

2017-03-11 02:42 UTC, brenoalvs commented on widgets/partials/public-monk-language-switcher.php
> +				Made with <span class="dashicons dashicons-heart monk-heart"></span> by <a href="https://github.com/brenoalvs/monk">Monk</a>
Localize and escape monk love message.

2017-03-11 02:42 UTC, brenoalvs commented on admin/class-monk-admin.php
> +	 * @since    0.3.0
Align doc tags values.

2017-03-11 02:42 UTC, brenoalvs commented on admin/class-monk-admin.php
> +		$appreciation = get_option( 'appreciate_monk', null ) ? true : false;
The `get_option` second parameter must be `false`.

2017-03-11 02:42 UTC, brenoalvs commented on public/css/monk-widget.css
> +	margin-top: 0.3em;
Why we're using `em` unit here? This value should be relative to font-size?

2017-03-11 02:42 UTC, brenoalvs commented on public/css/monk-widget.css
> +}
Coding standard: add a blank line to the end of file.

2017-03-11 02:42 UTC, brenoalvs commented on widgets/partials/public-monk-language-switcher.php
>  <?php echo $args['after_widget']; ?>
Coding standard: add a blank line to the end of file.

2017-03-24 00:31 UTC, leonofre commented on public/css/monk-widget.css
> +	margin-top: 0.3em;
To match the fonts in each theme, there could be varyances in them.

2017-03-29 17:08 UTC, closed without merging