Monk settings page enhancements
brenoalvs/monk pull request #239
Opened 2017-08-07 12:13 UTC by chandonn

This pull request relates to/fixes #238

2017-08-08 02:12 UTC, brenoalvs requested changes

2017-08-08 02:12 UTC, brenoalvs commented on admin/js/monk-admin.js
> +
Use PHP sort, avoid unnecessary DOM manipulations after page loads.
http://php.net/manual/pt_BR/function.sort.php

2017-08-08 09:58 UTC, chandonn commented on admin/js/monk-admin.js
> +
Since it will handle a multidimensional array, it's better use the `usort` function, with a lambda function

2017-08-09 01:50 UTC, brenoalvs requested changes

2017-08-09 01:50 UTC, brenoalvs commented on admin/css/monk-admin.css
> +.description {
Use `.monk-description` avoid global terms

2017-08-09 01:50 UTC, brenoalvs commented on includes/monk-functions.php
> +	uasort( $monk_languages,
Fix coding standard
```
uasort( $monk_languages, function( $a, $b ) {
	return strcmp( $a['english_name'], $b['english_name'] );
});
```

2017-08-09 04:32 UTC, brenoalvs approved these changes

2017-08-09 04:33 UTC, merged