Language column accessibility
brenoalvs/monk pull request #283
Opened 2017-08-23 03:55 UTC by chandonn

Fixes #191

2017-08-23 13:22 UTC, leonofre commented on admin/partials/monk-language-column.php
> +			<span class="monk-selector-flag flag-icon <?php echo esc_attr( 'flag-icon-' . $monk_languages[ $monk_language ]['slug'] ); ?>" aria-label="<?php echo esc_attr( $monk_languages[ $monk_language ]['e
Use 'esc_attr_e()' instead of 'echo esc_attr()'

2017-08-23 13:31 UTC, leonofre requested changes

2017-08-23 13:31 UTC, leonofre commented on admin/partials/monk-language-column.php
> +			<span class="monk-selector-flag flag-icon <?php echo esc_attr( 'flag-icon-' . $monk_languages[ $monk_language ]['slug'] ); ?>" aria-label="<?php echo esc_attr( $monk_languages[ $monk_language ]['e
These improvements should be implemented across all language flags, not just in language columns

2017-08-24 16:21 UTC, leonofre approved these changes

2017-08-26 22:56 UTC, brenoalvs approved these changes

2017-08-27 01:48 UTC, merged