Added improvements related to languages column
brenoalvs/monk pull request #96
Opened 2016-12-06 17:22 UTC by leonofre

Related to #80

2016-12-07 17:44 UTC, brenoalvs requested changes

2016-12-07 17:44 UTC, brenoalvs commented on admin/class-monk-admin.php
> +			$avaliable_languages  = false;
Variable misspeling: 
`$available_languages` not `$avaliable_languages`

2016-12-07 17:44 UTC, brenoalvs commented on admin/class-monk-admin.php
> +								'monk_term_id' => $monk_term_translations_id,
This parameter will be modified to `monk_id`

2016-12-07 17:44 UTC, brenoalvs commented on admin/partials/admin-taxonomy-monk-language-column.php
> +		<a class="monk-new-translation-link" href="<?php echo esc_url( $new_term_url ); ?>">Add +</a>
Localize label `__( 'Add+', 'monk' )`

2016-12-07 17:44 UTC, brenoalvs commented on admin/partials/monk-language-column.php
> +		<a class="monk-new-translation-link" href="<?php echo esc_url( $new_post_url ); ?>">Add +</a>
Localize label __( 'Add+', 'monk' )

2016-12-07 17:44 UTC, brenoalvs commented on admin/partials/monk-language-column.php
>  <?php
Fix `<?php else : ?>` code standard

2016-12-08 16:25 UTC, leonofre commented on admin/class-monk-admin.php
> +								'monk_term_id' => $monk_term_translations_id,
This is related to issue #79

2016-12-10 03:51 UTC, brenoalvs approved these changes

2016-12-10 03:51 UTC, merged