Term edition interface
brenoalvs/monk pull request #98
Opened 2016-12-06 21:05 UTC by leonofre

Related to #97

2016-12-07 17:55 UTC, brenoalvs requested changes

2016-12-07 17:55 UTC, brenoalvs commented on admin/class-monk-admin.php
> +		$avaliable_languages       = false;
Small misspelling it's `$available_languages` not ``$avaliable_languages``

2016-12-07 17:55 UTC, brenoalvs commented on admin/partials/admin-monk-term-translation.php
> +		if ( $translation_code === $language && $monk_language !== $language ) :
Why using 2 `foreach`?
At this line we can check by `in_array( $translation_code, $languages );`

2016-12-07 17:55 UTC, brenoalvs commented on admin/partials/admin-monk-term-translation.php
> +						'monk_term_id'     => $monk_term_translations_id,
We're changing this to `monk_id`

2016-12-07 17:55 UTC, brenoalvs commented on admin/partials/admin-monk-term-translation.php
> +					<p><?php esc_html_e( 'No Avaliable Translations!', 'monk' ); ?></p>
No Available...

2016-12-07 17:55 UTC, brenoalvs commented on admin/partials/admin-monk-term-translation.php
> +					<a href="<?php echo esc_url( $new_term_url ); ?>" class="button">Add a translation +</a>
Localize label `esc_html_e( 'Add a translation +' )`

2016-12-08 16:46 UTC, leonofre commented on admin/partials/admin-monk-term-translation.php
> +						'monk_term_id'     => $monk_term_translations_id,
This is related to issue #79

2016-12-10 03:52 UTC, brenoalvs approved these changes

2016-12-10 03:52 UTC, merged