Admin notice
brenoalvs/monk pull request #99
Opened 2016-12-06 21:11 UTC by chandonn

Related to #76

2016-12-07 17:51 UTC, brenoalvs requested changes

2016-12-07 17:51 UTC, brenoalvs commented on admin/partials/admin-monk-notice-render.php
> +		<a href="<?php esc_attr_e( 'admin.php?page=monk', 'monk' ); ?>" class="button button-primary"><?php esc_html_e( 'Go to Monk settings', 'monk' ); ?></a>
Wrong admin url and scaping, get `$settings_url` from method and `esc_url` function.

2016-12-07 17:51 UTC, brenoalvs commented on includes/class-monk.php
> +		$settings_url = admin_url( 'admin.php?page=monk' );
Align `=` signs

2016-12-07 17:51 UTC, brenoalvs commented on includes/class-monk.php
> +		if ( ! empty( $monk_activated ) ) {
When this option is updated?

2016-12-10 03:56 UTC, leonofre requested changes

2016-12-10 03:56 UTC, leonofre commented on admin/partials/admin-monk-notice-render.php
> +	<p><?php printf( __( '<strong>Monk:</strong> You need to <a href="%s">configure your language preferences</a>.' ), admin_url( 'admin.php?page=monk' ) ); ?></p>
Add text domain

2016-12-10 03:58 UTC, brenoalvs approved these changes

2016-12-10 03:58 UTC, leonofre approved these changes

2016-12-10 03:58 UTC, merged